/*
Script para criação dos candidatos da eleição 
de Borá 2016 - Vereador
*/

USE totaliza;

INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (45045, 'ADVALDO CELESTINO TEIXEIRA', 'DU', '1976-12-01', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN coligacao ON partido_coligacao_eleicao.coligacao_id = coligacao.id WHERE coligacao.nome = 'RUMO NOVO COM A FORÇA DO POVO'));
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (45330, 'ANGELO APARECIDO DA SILVA', 'NICO', '1976-06-25', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN coligacao ON partido_coligacao_eleicao.coligacao_id = coligacao.id WHERE coligacao.nome = 'RUMO NOVO COM A FORÇA DO POVO'));
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (10222, 'DOMILSON DOMINGOS DOS SANTOS', 'GOIANO', '1976-07-22', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN coligacao ON partido_coligacao_eleicao.coligacao_id = coligacao.id WHERE coligacao.nome = 'RUMO NOVO COM A FORÇA DO POVO'));
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (10614, 'PEDRO CORREIA DA COSTA', 'PEDRO CORREIA','1964-03-14', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN coligacao ON partido_coligacao_eleicao.coligacao_id = coligacao.id WHERE coligacao.nome = 'RUMO NOVO COM A FORÇA DO POVO'));
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (10000, 'VALDIR PEDRO DA SILVA', 'TIBIRA','1970-07-12', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN coligacao ON partido_coligacao_eleicao.coligacao_id = coligacao.id WHERE coligacao.nome = 'RUMO NOVO COM A FORÇA DO POVO'));
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (10111, 'IVANETE MAXIMINA DE CARVALHO', 'NETE', '10111', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN coligacao ON partido_coligacao_eleicao.coligacao_id = coligacao.id WHERE coligacao.nome = 'RUMO NOVO COM A FORÇA DO POVO'));
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (10430, 'MARIO PEDRO DA SILVA', 'MARIÃO', '1977-12-06', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN coligacao ON partido_coligacao_eleicao.coligacao_id = coligacao.id WHERE coligacao.nome = 'RUMO NOVO COM A FORÇA DO POVO'));
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (10100, 'APARECIDO DOMINGOS RICARDO', 'CIDINHO', '1954-08-04', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN coligacao ON partido_coligacao_eleicao.coligacao_id = coligacao.id WHERE coligacao.nome = 'RUMO NOVO COM A FORÇA DO POVO'));
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (10333, 'ARTUR ROQUE CALDAS', 'ARTUR CALDAS', '1951-11-10', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN coligacao ON partido_coligacao_eleicao.coligacao_id = coligacao.id WHERE coligacao.nome = 'RUMO NOVO COM A FORÇA DO POVO'));
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (45555, 'CRISTIAN DIOGO DOS SANTOS', 'DIOGO', '1984-02-19', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN coligacao ON partido_coligacao_eleicao.coligacao_id = coligacao.id WHERE coligacao.nome = 'RUMO NOVO COM A FORÇA DO POVO'));
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (45022, 'ANTONIO VITORINO SOARES', 'TONINHO PRETO', '1969-09-13', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN coligacao ON partido_coligacao_eleicao.coligacao_id = coligacao.id WHERE coligacao.nome = 'RUMO NOVO COM A FORÇA DO POVO'));
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (43000, 'ADRIANA GONÇALVES DE OLIVEIRA', 'ADRIANA', '1985-03-22', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN coligacao ON partido_coligacao_eleicao.coligacao_id = coligacao.id WHERE coligacao.nome = 'RUMO NOVO COM A FORÇA DO POVO'));
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (45444, 'IVANILDE PEREIRA DA COSTA E SILVA', 'IVANILDE', '1972-09-19', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN coligacao ON partido_coligacao_eleicao.coligacao_id = coligacao.id WHERE coligacao.nome = 'RUMO NOVO COM A FORÇA DO POVO'));
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (45032, 'WILSON AZEVEDO', 'WILSON AZEVEDO', '1931-03-14', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN coligacao ON partido_coligacao_eleicao.coligacao_id = coligacao.id WHERE coligacao.nome = 'RUMO NOVO COM A FORÇA DO POVO'));
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (10125, 'AUGUSTO MANOEL MERCI', 'NEGÃO DO BAR', '1958-01-24', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN coligacao ON partido_coligacao_eleicao.coligacao_id = coligacao.id WHERE coligacao.nome = 'RUMO NOVO COM A FORÇA DO POVO'));
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (45500, 'RENATA DA CONCEIÇÃO DA SILVA', 'RENATA', '1977-06-16', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN coligacao ON partido_coligacao_eleicao.coligacao_id = coligacao.id WHERE coligacao.nome = 'RUMO NOVO COM A FORÇA DO POVO'));
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (10900, 'VANIA MARIA DA SILVA', 'VANIA', '1983-12-29', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN coligacao ON partido_coligacao_eleicao.coligacao_id = coligacao.id WHERE coligacao.nome = 'RUMO NOVO COM A FORÇA DO POVO'));
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES ('10950', 'SILVANA DE BEN PEDRO DA SILVA', 'SILVANA', '1984-11-18', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN coligacao ON partido_coligacao_eleicao.coligacao_id = coligacao.id WHERE coligacao.nome = 'RUMO NOVO COM A FORÇA DO POVO'));

INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (40650, 'PAULO SERGIO DOS SANTOS', 'PAULO MECÂNICO', '1978-04-22', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN coligacao ON partido_coligacao_eleicao.coligacao_id = coligacao.id WHERE coligacao.nome = 'PSB/PT')); 
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (13111, 'PAULO ROBERTO GONÇALVES GUSMÃO', 'PAULINHO', '1983-09-11', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN coligacao ON partido_coligacao_eleicao.coligacao_id = coligacao.id WHERE coligacao.nome = 'PSB/PT')); 
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (40123, 'ROBSON DONLEY', 'ROBSON', '1964-01-29', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN coligacao ON partido_coligacao_eleicao.coligacao_id = coligacao.id WHERE coligacao.nome = 'PSB/PT')); 
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (13555, 'EDSON ALVES DOS SANTOS', 'EDSON LAGOA', '1984-04-30', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN coligacao ON partido_coligacao_eleicao.coligacao_id = coligacao.id WHERE coligacao.nome = 'PSB/PT')); 
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (40014, 'ADELINA MENDES DOS SANTOS', 'TIA DILA', '1956-08-23', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN coligacao ON partido_coligacao_eleicao.coligacao_id = coligacao.id WHERE coligacao.nome = 'PSB/PT')); 
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (40100, 'ADEMIR FERREIRA', 'ADEMIR - PÉ', '1967-01-27', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN coligacao ON partido_coligacao_eleicao.coligacao_id = coligacao.id WHERE coligacao.nome = 'PSB/PT')); 
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (40190, 'ATAIDE RODRIGUES', 'IRMÃO CABO RODRIGUES', '1968-01-14', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN coligacao ON partido_coligacao_eleicao.coligacao_id = coligacao.id WHERE coligacao.nome = 'PSB/PT')); 
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (13213, 'APARECIDA NATALINA PEREIRA', 'CIDA', '1965-12-16', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN coligacao ON partido_coligacao_eleicao.coligacao_id = coligacao.id WHERE coligacao.nome = 'PSB/PT')); 
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (13567, 'WILSON CANATO', 'NENO', '1959-09-25', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN coligacao ON partido_coligacao_eleicao.coligacao_id = coligacao.id WHERE coligacao.nome = 'PSB/PT')); 
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (40456, 'LUZIA DA CONCEIÇÃO FERREIRA', 'LUZIA FERREIRA', '1967-08-17', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN coligacao ON partido_coligacao_eleicao.coligacao_id = coligacao.id WHERE coligacao.nome = 'PSB/PT')); 
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (40040, 'LUIS EZEQUIEL DA SILVA JUNIOR', 'PASTOR JUNIOR', '1968-01-24', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN coligacao ON partido_coligacao_eleicao.coligacao_id = coligacao.id WHERE coligacao.nome = 'PSB/PT')); 
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (40521, 'GIDEON PROSPERO DE SANTANA', 'SANTANA SEGURANÇA', '1949-11-29', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN coligacao ON partido_coligacao_eleicao.coligacao_id = coligacao.id WHERE coligacao.nome = 'PSB/PT')); 
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (13222, 'MARIA LUCIANA DA SILVA', 'LUCIANA DA SAUDE', '1979-05-30', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN coligacao ON partido_coligacao_eleicao.coligacao_id = coligacao.id WHERE coligacao.nome = 'PSB/PT')); 
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (13002, 'MARCIA APARECIDA MARTINS', 'MARCIA DO TRAILER', '1978-06-15', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN coligacao ON partido_coligacao_eleicao.coligacao_id = coligacao.id WHERE coligacao.nome = 'PSB/PT'));
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (40111, 'MARCIA LUCIANE DA SILVA', 'MARCIA LUCIANE', '1980-12-23', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN coligacao ON partido_coligacao_eleicao.coligacao_id = coligacao.id WHERE coligacao.nome = 'PSB/PT')); 

INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (55444, 'JOSE DE SOUZA', 'ZÉ BRANCO', '1956-08-06', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN partido ON partido_coligacao_eleicao.partido_id = partido.id WHERE partido.sigla = 'PSD'));
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (55020, 'DEVANIR PEREIRA DA ROCHA', 'DEVANIR NIM', '1972-10-12', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN partido ON partido_coligacao_eleicao.partido_id = partido.id WHERE partido.sigla = 'PSD'));
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (55555, 'JOE FRANCISCO RODRIGUES', 'JOE FRANCIS', '1990-02-15', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN partido ON partido_coligacao_eleicao.partido_id = partido.id WHERE partido.sigla = 'PSD'));
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (55015, 'LUIS CARLOS TOMAZ', 'CARLINHOS DO DIVINO', '1971-08-15', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN partido ON partido_coligacao_eleicao.partido_id = partido.id WHERE partido.sigla = 'PSD'));
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (55000, 'ELIANA APARECIDA MAYOLLI', 'ELIANA MAYOLLI', '1975-04-24', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN partido ON partido_coligacao_eleicao.partido_id = partido.id WHERE partido.sigla = 'PSD'));
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (55191, 'SUELI DE JESUS CARVALHO', 'SUELI CARVALHO', '1958-11-19', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN partido ON partido_coligacao_eleicao.partido_id = partido.id WHERE partido.sigla = 'PSD'));
INSERT INTO `totaliza`.`candidato` (`numero`, `nome`, `nome_urna`, `data_nascimento`, `partido_coligacao_eleicao_id`) VALUES (55545, 'MARIA JOSE DE AZEVEDO', 'ZEZINHA', '1959-08-04', (SELECT partido_coligacao_eleicao.id from partido_coligacao_eleicao INNER JOIN partido ON partido_coligacao_eleicao.partido_id = partido.id WHERE partido.sigla = 'PSD'));
